services:
  collecte-backend:
    image: ghcr.io/sim-assurances/collectapp-backend:v4
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://postgres:RepensTOI@collecte-mysim-collecte-nfmnqg:5432/collecteApp
      JWT_SECRET: c1ab8d3b389eaae3dbe3ab288f7e6ca3f5a6e113ad6b0f752a4daf5d0079062879b562c396eb5365082996ab46f2caa8b890849967c4845367d283fbd30db0ad
      JWT_EXPIRES_IN: 24h
      CORS_ORIGIN: https://collecte.mysimassurances.com
      WAVE_API_KEY: VOTRE_CLE_API_WAVE_ICI
    networks:
      - dokploy-network
    restart: unless-stopped

  collecte-frontend:
    image: ghcr.io/sim-assurances/collectapp-frontend:v6
    depends_on:
      - collecte-backend
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
